package cn.leancloud.leancloud_message;



interface Session {
  int OPERATION_SEND_MESSAGE = 10000;
  int OPERATION_WATCH_PEERS = 10001;
  int OPERATION_UNWATCH_PEERS = 10002;
  int OPERATION_SET_TIMEOUT = 10003;
  int OPERATION_OPEN_SESSION = 10004;
  int OPERATION_CLOSE_SESSION = 10005;
  int OPERATION_ONLINE_QUERY = 10006;
  int OPERATION_UNKNOW = -1;

  int DEFAULT_SESSION_TIMEOUT_SECS = 15;

  String PARAM_SESSION_PEERIDS = "PARAM_SESSION_PEERIDS";
  String PARAM_SESSION_TAG = "PARAM_SESSION_TAG";

  String AV_SESSION_PREFERENCE_MESSAGE_KEY = "AV_SESSION_PREFERENCE_MESSAGE_KEY";
  String AV_SESSION_PREFERENCE_PEERIDS_KEY = "AV_SESSION_PREFERENCE_PEERIDS_KEY";
  String AV_SESSION_PREFERENCE_ONLINE_KEY = "AV_SESSION_INTENT_SELFID_KEY";
  String AV_SESSION_PREFERENCE_OFFLINE_KEY = "AV_SESSION_PREFERENCE_OFFLINE_KEY";
  String AV_SESSION_INTENT_ACTION = "com.avoscloud.session.action";
  String AV_SESSION_INTENT_SELFID_KEY = "AV_SESSION_INTENT_SELFID_KEY";
  String AV_SESSION_INTENT_OPERATION_KEY = "AV_SESSION_INTENT_OPERATION_KEY";
  String AV_SESSION_INTENT_DATA_KEY = "AV_SESSION_INTENT_DATA_KEY";
  String AV_SESSION_INTENT_STATUS_KEY = "AV_SESSION_INTENT_STATUS_KEY";
  String AV_SESSION_INTENT_THROWABLE_KEY = "AV_SESSION_INTENT_THROWABLE_KEY";

  int STATUS_SESSION_OPEN = 20000;
  int STATUS_SESSION_PAUSE = 20001;
  int STATUS_SESSION_RESUME = 20002;
  int STATUS_SESSION_ONMESSAGE = 20003;
  int STATUS_SESSION_ONMESSAGESEND = 20004;
  int STATUS_SESSION_ONMESSAGEFAILURE = 20005;
  int STATUS_SESSION_ONSTATUSONLINE = 20006;
  int STATUS_SESSION_ONSTATUSOFFLINE = 20007;
  int STATUS_SESSION_ONERROR = 20008;
  int STATUS_SESSION_QUERY_CALLBACK = 20009;
  int STATUS_SESSION_ONPEERSWATCHED = 20010;
  int STATUS_SESSION_ONPEERSUNWATCHED = 20011;
  int STATUS_SESSION_ONMESSGEDELIVERED = 20012;
  int STATUS_SESSION_CLOSE = 20013;

  int SESSION_PACKET_MAX_LENGTH = 5000;
  int SESSION_PEERID_MAX_SIZE = 100;

  String ERROR_INVALID_SESSION_ID = "Null id in session id list.";
}
